"""crear tabla Photo

Revision ID: 2902a1adf666
Revises: 
Create Date: 2025-08-12 17:13:33.932775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2902a1adf666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('author_link', sa.String(length=512), nullable=False),
    sa.Column('camera_model', sa.String(length=255), nullable=False),
    sa.Column('exposure_time', sa.String(length=50), nullable=False),
    sa.Column('aperture', sa.String(length=50), nullable=False),
    sa.Column('focal_length', sa.String(length=50), nullable=False),
    sa.Column('iso', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
