"""agregado campo marca_camara

Revision ID: 4a9d9bb785bc
Revises: 2902a1adf666
Create Date: 2025-08-12 22:32:01.459367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9d9bb785bc'
down_revision = '2902a1adf666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_mark', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('camera_mark')

    # ### end Alembic commands ###
